
const menuList =[
  {
    menuName:'系统管理',
    path:'/system',
    _id:'jkl323123',
    menuType:1,
    children:[
      {
        menuName:'用户管理',
        path:'/user',
        _id:'jfsdf7893',
        menuType:1,
      },
      {
        menuName:'菜单管理',
        path:'/system//menuManage',
        _id:'fsvcs657hd',
        menuType:1,
      },
      {
        menuName:'角色管理',
        path:'/system//roleManage',
        _id:'fdscn03',
        menuType:1,
      },
      {
        menuName:'部门管理',
        path:'/system//depManage',
        _id:'fsdcchu58895',
        menuType:1,
      },
    ]
  },
  {
    menuName:'审批管理',
    path:'/approvalManage',
    _id:'fscgsfml999',
    menuType:1,
    children:[
      {
        menuName:'休假申请',
        path:'/system//vacationApply',
        _id:'fscsgse234',
        menuType:1,
      },
      {
        menuName:'待我审批',
        path:'/system//dealByMine',
        _id:'fscsgsyr6745',
        menuType:1,
      },
    ]
  }
]
export  {
  menuList
}