const menuData = [
  {
    menuName:'系统管理',
    icon:'system',
    menuType:'菜单',
    permission:'',
    routerAddress:'system',
    componentRoute:'',
    menuStatus:1,
    createTime:'2022-03-17',
    _id:'jfksdj7',
    children:[
      {
        menuName:'用户管理',
        icon:'user',
        menuType:'菜单',
        permission:'',
        routerAddress:'system/user',
        componentRoute:'system/user',
        menuStatus:1,
        createTime:'2022-03-17',
        _id:'fsdlfsnfsd789'
      },
      {
        menuName:'菜单管理',
        icon:'user',
        menuType:'菜单',
        permission:'',
        routerAddress:'system/menuManage',
        componentRoute:'system/menuManage',
        menuStatus:1,
        createTime:'2022-03-17',
        _id:'fsdfsdgsghs'
      },
    ]
  },
  {
    menuName:'审批管理',
    icon:'approvalManage',
    menuType:'菜单',
    permission:'',
    routerAddress:'approvalManage',
    componentRoute:'',
    menuStatus:1,
    createTime:'2022-03-17',
    _id:'fsdfsdn8989',
    children:[
      {
        menuName:'休假申请',
        icon:'user',
        menuType:'菜单',
        permission:'',
        routerAddress:'approvalManage/user',
        componentRoute:'approvalManage/user',
        menuStatus:1,
        createTime:'2022-03-17',
        _id:'fsdfsdf42342'
      },
      {
        menuName:'待审批',
        icon:'user',
        menuType:'菜单',
        permission:'',
        routerAddress:'approvalManage/menuManage',
        componentRoute:'approvalManage/menuManage',
        menuStatus:1,
        createTime:'2022-03-17',
        _id:'fnsdjfh898'
      },
    ]
  }
]

export {
  menuData
}